//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFL.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.MovieActors = new HashSet<MovieActor>();
            this.MovieDirectors = new HashSet<MovieDirector>();
        }
    
        public int MovieID { get; set; }
        public string MovieTitle { get; set; }
        public int GenreID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int ProductionID { get; set; }
        public string Plot { get; set; }
        public string PosterImage { get; set; }
    
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieActor> MovieActors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieDirector> MovieDirectors { get; set; }
        public virtual ProductionCompany ProductionCompany { get; set; }
    }
}
